short term fix google_analytics deprecation
Scout24/mkdocs-material pull request #3
Opened 2021-06-07 15:36 UTC by oli99sc

in mkdocs 1.2: https://www.mkdocs.org/about/release-notes/#backward-incompatible-changes-in-12

2021-06-07 15:56 UTC, mlefringhausen commented on requirements.txt
> +mkdocs>=1 <1.2
```suggestion
mkdocs>=1, <1.2
```
I believe a "," is needed here: https://www.python.org/dev/peps/pep-0508/#examples

2021-06-07 15:57 UTC, mlefringhausen requested changes
I believe a "," is needed here: https://www.python.org/dev/peps/pep-0508/#examples

2021-06-08 06:23 UTC, oli99sc commented
@mlefringhausen thx for pointing this out. Is fixed.

2021-06-08 07:19 UTC, mlefringhausen approved these changes

2021-06-08 07:19 UTC, merged